# Generated by Django 5.0.1 on 2024-01-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='teste', unique=True),
            preserve_default=False,
        ),
    ]
