# Generated by Django 5.0.1 on 2024-01-31 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productinventory_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={'verbose_name': 'Inventário de produto', 'verbose_name_plural': 'Inventário de produtos'},
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productinventory',
            unique_together={('product', 'local')},
        ),
    ]
